### ISSUE TITLE
Consecutive command to multiple mappings leads to panic.

### ISSUE THREAD

**Issue by abarisani** [gsora/fidati#5]
Please see this [PR](https://github.com/transparency-dev/armored-witness-os/pull/39) which highlights the issue.

**Comment by gsora** [comment]
Can you compile with the `fidati_logs` build tag and provide logs? Thanks.

**Comment by gsora** [comment]
Please try latest `master`, `Tx` and `Rx` are now synchronized and no `Handler.state` corruption should happen.
